name: hello-world
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - names: Run a one-line script
        run: echo "Hello, world!"
